server:
  port: 60101
  
###################  服务配置  ###################
bdtd:
  swagger-open: true #是否开启swagger (true/false)
  multiple-db: false
  file-upload-path: d:/bdtd/upload
  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒

###################  beetl配置  ###################
beetl:
  delimiter-statement-start: \@   #开始结束标签(yml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
  resource-tagsuffix: tag
  resource-auto-check: true #是否检测文件变化,开发用true合适，但线上要改为false
  
###################  spring配置  ###################
spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: false #是否开启开发者工具（true/false）
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  http:
    converters:
      preferred-json-mapper: fastjson
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/bdtd/card/data/**/dao/mapper/*Mapper.xml
  type-aliases-package: com.bdtd.card.data.*.model
  global-config:
    db-config:
      id-type: auto  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
  
---    
##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  datasource:
    url:  jdbc:p6spy:mysql://47.96.90.230:3306/stock1?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    db-name: stock1
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      auto-commit: false
      connection-timeout: 30000
      idle-timeout: 25000
      login-timeout: 5
      max-lifetime: 30000
      read-only: false
      validation-timeout: 3000
      maximum-pool-size: 15
      minimum-idle: 10
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
#  quartz:
#    job-store-type: jdbc

logging:
#  config: classpath:log4j2.xml
  level:
    root: info
#  level.com.bdtd.card: debug
#  level.com.bdtd.card.data.admin.dao: debug
#  level.com.stylefeng.guns.core.aop.FileLogAop: debug
  path: logs/
  file: stock.log

stock:
  analyse:
    max-mid-increase: 2
    min-mid-increase: 2
    min-increase: 5
    